---

sudo: required

env:
  global: 
    - rolename : ansible-role-ipaserver
  matrix:
    - distribution: centos       # Linux distribution
      version: 6                 # Distribution version
    - distribution: centos
      version: 7
    - distribution: fedora
      version: 25
    # - distribution: ubuntu
    #   version: 14.04
    #   run_opts: ""
    # - distribution: ubuntu
    #   version: 12.04
    #   run_opts: ""

services: docker

before_install:
  # Install latest Git
  - sudo apt-get install --only-upgrade git 


before_script:
  # Fetch the latest test code for the role
  - 'git clone --depth 1 https://github.com/yabhinav/ansible-test-suite'
  - mv ansible-test-suite/$rolename/* . &&  rm -rf ansible-test-suite

script:
  # Create container and load the role as a volume
  - ./docker-tests.sh


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
