---

# Refer https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Identity_Management_Guide/installing-ipa.html#Installing_the_IPA_Server_Packages
- block:
    - name: Run the IPA Server installer
      shell :
       "{{ ipaserver_base_command }}
        --realm {{ ipaserver_realm }}
        --domain {{ ipaserver_domain }}
        -a {{ ipaserver_admin_password }}
        -p {{ ipaserver_dir_admin_password }}
        --hostname={{ ansible_fqdn }}
        --ip-address={{ ansible_default_ipv4.address | default(ansible_eth0.ipv4.address) }}
        {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart | default(False) else '' }}
        {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax | default(False) else '' }}
        {{ '--setup-dns' if ipaserver_setup_dns | default(False) else '' }}
        {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(False) else '' }}
        {{ '--forwarder=%s' % ipaserver_dns_forwarder
           if ipaserver_dns_forwarder | default(False) and ipaserver_setup_dns | default(False) else '--no-forwarders' }}
        {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }}
        {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }}
        {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }}
        {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }}
        {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }}"  
      args:
        creates: /etc/ipa/setup_ansible.done
      register: ipasetup
  always:
  # Mark Server Configuration Done 
    - name: Set IPA Server Install and Configuring Done
      file: dest=/etc/ipa/setup_ansible.done state=touch mode=0755
      when: "ipasetup.changed and 'Setup complete' in ipasetup.stdout "
  become: True