---

# Refer https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/identity_management_guide/creating-the-replica
- block:

    - delegate_to: '{{ ipaserver_replica_master }}'
      block:

        - name: Create the replica information file on the master
          debug:

        - name: Create a temporary directory on the control host
          debug:

        - name: Copy the replica information file to temporary directory
          debug:

        - name: Copy the replica information file to the replica
          debug:

      always:

        - name: Remove the temporary directory on the control host
          debug:

        - name: Remove the replica information file from the master
          debug:

    - name: Run the IPA replica installer
      shell: false
      args:
        creates: /etc/ipa/setup_ansible.done
      register: ipasetup

  always:

    - debug: var=ipasetup

    - name: Set IPA Server Install and Configuring Done
      file: dest=/etc/ipa/setup_ansible.done state=touch mode=0755
      when: ipasetup is successful and ipasetup is changed
