---

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
   - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "../vars/{{ ansible_distribution }}.yml"
   - "../vars/{{ ansible_os_family }}.yml"
   - "../vars/defaults.yml"

- name: Install IPA Server Packages
  action: >
    {{ ansible_pkg_mgr }} name="{{ item }}" state=latest
  with_items: "{{ ipaserver_packages }}"
  become: True

- name: Free-up modnss TCP port
  include: modssl_config.yml

- name: Ubuntu fixes
  include: pam_sssd_config.yml
  when: '{{ ansible_os_family }} == "Debian" '

- name: Install IPA Server
  include: ipainstall.yml

- name: Start IPA Server
  include: ipastart.yml

- name: check for TGT and Kinit
  include: kinit.yml

- name: Generate HTTP Keytab for IPA Web Server
  include: ipahttp.yml

