---

- name: Gather OS Specific Variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "defaults.yml"

- name: Install IPA Server Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ipaserver_packages }}"

- name: Free-up modnss TCP port
  include: modssl_config.yml

- name: Ubuntu fixes
  include: pam_sssd_config.yml
  when: ansible_os_family == 'Debian'

- name: Install IPA Server
  include: ipainstall.yml
  when: not ipaserver_replica_master | trim | length

- name: Install IPA Replica
  include: ipareplica.yml
  when: ipaserver_replica_master | trim | length

- name: Start IPA Server
  include: ipastart.yml

- name: check for TGT and Kinit
  include: kinit.yml

- name: Generate HTTP Keytab for IPA Web Server
  include: ipahttp.yml
