---

- name: Install IPA Server Packages
  yum: name="{{ item }}" state=present
  with_items: "{{ ipaserver_packages }}"
  become: True

- name: Free-up modnss TCP port
  include: modssl_config.yml

- name: Install IPA Server
  include: ipainstall.yml

- name: Start IPA Server
  include: ipastart.yml

# Making Sure TGT is available for next steps
- block:
    - name: Check for Valid Kerberos TGT Cache
      shell: "klist -s"
      changed_when: False
  rescue:
    - name: Kinit IPA Admin
      script: ./library/kinit.exp {{ ipaserver_admin_username }} {{ ipaserver_admin_password }} {{ ipaserver_realm }}
      no_log: True
  become: True

- name: Generate HTTP Keytab for IPA Web Server
  include: ipahttp.yml

